# 指定项目启动端口号
server:
  port: 3010
spring:
  # 配置数据库连接（基本是固定写法）
  datasource:
    username: root
    password: lMXhnTAVdYGbGg8yPg7BShHC/QyluPhrGdVogm5bCw9NIli4QB4rmIKk61+d+uhs3f70KvTFUg70WMNValZKSQ==
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.80.181:3306/jc_club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    # 配置数据库连接池，本项目使用的是druid，所以配置durid即可，没有配置连接池则不写该项，使用默认的即可
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置druid连接池的详细信息
    druid:
      initial-size: 20  # 初始化连接数
      min-idle: 20      # 最小空闲连接数
      max-active: 100   # 最大活跃连接数
      max-wait: 60000   # 获取连接时最大等待时间，单位毫秒
      # 配置数据库密码加密，password处写加密后的密码，publicKey是加密的公钥
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      # Druid监控配置
      stat-view-servlet:
        enabled: true            # 启用Druid监控页面
        url-pattern: /druid/*    # 监控页面的访问URL模式
        login-username: admin    # 监控页面的登录用户名
        login-password: 123456   # 监控页面的登录密码
      # Druid过滤器配置
      filter:
        # 监控统计拦截,用于统计和监控数据库连接的使用情况
        stat:
          enabled: true           # 启用stat过滤器
          slow-sql-millis: 2000   # 慢SQL阈值，单位毫秒
          log-slow-sql: true      # 记录慢SQL
        # 防御SQL注入
        wall:
          enabled: true   # 启用wall过滤器
        config:
          enabled: true   # 启用config过滤器，这个过滤器主要用于加载配置，通常不直接用于业务功能
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 117.72.80.181
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 2s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
# 加密后的公钥
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALBTAJ3Cq067Nk3qhlOEUW6SV1aqLqabQUPz2ZCctoJ3sIW5ROMabRQVYlkGdFyJX70dgcf+8F6c46iFJlgQvzkCAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml
es:
  cluster:
    esConfigs[0]:
      name: 4240245a487c
      nodes: 117.72.80.181:9200
# 多个集群的话就在下面接着配esConfigs[1]、esConfigs[2]等等
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: yiqu-club-subject
      address:
      ip: 127.0.0.1
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
## 打印日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 117.72.80.181:9876
  producer:
    group: test-group
