server:
  port: 3000
spring:
  datasource:
    username: root
    password: DNlyDIZEzRv3qUSRj1LfKsBRKqUnOQnMG7NUskvIrtxgojtfdNDStLT8/ptWpyElMzm7LioQD0AhQv6u1NbJnA==
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.17.128:3306/jc_club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJoyV0bOMP3yG3cusJuVGjpUl0fwcacMHrCtulE0mA4sR154p1JylHJLbroEQIkbHwFwBmnm7KgAdBVVIPfp91cCAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml
# 打印日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl